config/routes.rb
Rails.application.routes.draw do

   root 'feed#index'
   devise_for :users
   resources :favorites

end

app/models/favorite.rb
class Favorite < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :favorites, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_user
  before_action :set_favorite, only: [:show, :edit, :update, :destroy]

  # GET /favorites
  # GET /favorites.json
  def index
    @favorites = @user.favorites.all
  end

  # GET /favorites/1
  # GET /favorites/1.json
  def show
  end

  # GET /favorites/new
  def new
    @favorite = @user.favorites.new
  end

  # GET /favorites/1/edit
  def edit
  end

  # POST /favorites
  # POST /favorites.json
  def create
    @favorite = @user.favorites.new(favorite_params)
    respond_to do |format|
      if @favorite.save
        format.js
      else
        format.html { render :new }
        format.json { render json: @favorite.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /favorites/1
  # PATCH/PUT /favorites/1.json
  def update
    respond_to do |format|
      if @favorite.update(favorite_params)
        format.html { redirect_to @favorite, notice: 'Favorite was successfully updated.' }
        format.json { render :show, status: :ok, location: @favorite }
      else
        format.html { render :edit }
        format.json { render json: @favorite.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /favorites/1
  # DELETE /favorites/1.json
  def destroy
    @favorite.destroy
    respond_to do |format|
      format.html { redirect_to favorites_url, notice: 'Favorite was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Define User that owns favorites
    def set_user
        @user = current_user
    end
    # Use callbacks to share common setup or constraints between actions.
    def set_favorite
      @favorite = @user.favorites.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def favorite_params
      params.permit(:title, :url, :user_id)
    end
end

app/controllers/feed_controller.rb
class FeedController < ApplicationController
  # Main Feed View
  # GET /
  def index
    # Set a default parameter if no specific feed is given
    if params[:feedurl].blank?
      @url = "http://www.treehugger.com/feeds/category/cars/"
    else
      @url = params[:feedurl].to_s
    end
    @feed = Feedjira::Feed.fetch_and_parse @url
    @title  = @feed.title.to_s + " From " + @feed.url.to_s
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/feed_helper.rb
module FeedHelper
end

app/views/favorites/_form.html.erb
<%= form_for(@favorite) do |f| %>
  <% if @favorite.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@favorite.errors.count, "error") %> prohibited this favorite from being saved:</h2>

      <ul>
      <% @favorite.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :url %><br>
    <%= f.text_field :url %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/favorites/edit.html.erb
<h1>Editing Favorite</h1>

<%= render 'form' %>

<%= link_to 'Show', @favorite %> |
<%= link_to 'Back', favorites_path %>

app/views/favorites/index.html.erb
<p id="notice"><%= notice %></p>

<h1>My Favorites</h1>
<ul class="list-group">
  <% @favorites.each do |favorite| %>
    <li class="list-group-item"><%= link_to favorite.title, favorite.url %></li>
  <% end %>
</ul>

app/views/favorites/new.html.erb
<h1>New Favorite</h1>

<%= render 'form' %>

<%= link_to 'Back', favorites_path %>

app/views/favorites/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @favorite.title %>
</p>

<p>
  <strong>Url:</strong>
  <%= @favorite.url %>
</p>

<%= link_to 'Edit', edit_favorite_path(@favorite) %> |
<%= link_to 'Back', favorites_path %>

app/views/feed/index.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
      Currently Showing - <%= @title %>
  </div>
  <div class="panel-body">
    <%= form_tag root_path, method: :get do %>
      <%= label_tag :feedurl, "Please enter URL of RSS Feed you want to view here:" %>
      <%= text_field_tag :feedurl, "", :class => 'form-control' %>
      <%= submit_tag "Update Feed", name: nil, :class => "btn btn-primary" %>
      <% end %>
  </div>
</div>
<div class="panel panel-default">
  <div class="panel-heading">
    <%= @title %>
  </div>
  <ul class="list-group">
    <% unless @feed.nil? %>
      <% @feed.entries.each do |entry| %>
      <li class="list-group-item"><%= link_to entry.title, entry.url %>
        <% if user_signed_in? && current_user.favorites.find_by_title(entry.title).blank? %>
          <span id="favoriter"> - <%= link_to "Add To Favorites", { :controller => "favorites",
                                                                                                          :action => "create",
                                                                                                          :user_id => current_user.id,
                                                                                                          :title => entry.title,
                                                                                                          :url => entry.url},
                                                                                                          method: :post,
                                                                                                          remote: true %>
          </span>
        <% elsif user_signed_in?  %>
         - Already a favorite.
        <% else %>
          - <%= link_to "Sign In To Favorite", new_user_session_path %></li>
        <% end %>
        </li>
      <% end %>
    <% end %>
  </ul>
  <script type="text/javascript">
    $(function(){
      $("#favoriter").on("click",function(){
        $(this).fadeOut();
        $(this).parent('li').append("Already a favorite")
      });
    });
  </script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RssfeedTest</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "RSS Feed/Favoriter", root_path, :class => "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to "Favorites", favorites_path %></li>
      </ul>
      <ul class="nav navbar-right">
        <% if user_signed_in? %>
          <li><%= "Logged in as " + current_user.email %></li>
          <li><%= link_to "Log Out", destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to "Sign In To Use Favorites!", new_user_session_path %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>


<%= yield %>

</body>
</html>